<div class="content">
    <?php
    	if(isset($_GET['xem'])){
			$tam=$_GET['xem'];
		}else{
			$tam='';
		}if($tam=='chitiet'){
			include('noidung/chitiet.php');
		}elseif($tam=='dangky'){
			include('noidung/dangky.php');
		}elseif($tam=='thongbao'){
			include('noidung/thongbao.php');
		}elseif($tam=='mathang'){
			include('noidung/mathang.php');
		}elseif($tam=='nhanhieu'){
			include('noidung/nhanhieu.php');
		}elseif($tam=='giohang'){
			include('noidung/giohang.php');
		}elseif($tam=='update_cart'){
			include('noidung/update_cart.php');
		}elseif($tam=='dangnhap'){
			include('noidung/dangnhap.php');
		}elseif(isset($_POST['search'])){
			include('noidung/search.php');
		}
		else{
			include('noidung/sanpham.php');
		}
	?>
</div>
<div class="clear"></div>