<?php
	if(isset($_GET['ac'])){
		$tam=$_GET['ac'];
	}else{
		$tam='';
	}if($tam=='them'){
		include('modules/quanlymathang/them.php');
	}if($tam=='sua'){
		include('modules/quanlymathang/sua.php');
	}if($tam=='lietke'){
		include('modules/quanlymathang/lietke.php');
	}
?>
